name: pcb-yolo
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
      - ultralytics
      - ensemble-boxes
      - roboflow
      - pyyaml
      - matplotlib
      - pandas
